spring:
    application:
        name: telemedicine
    datasource:
      url: jdbc:postgresql://localhost:5432/telemedicine
      username: postgres
      password: password
    jpa:
      show-sql: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400

gemini:
  api-key: ${GEMINI_API_KEY}

file:
  encryption:
    secret: ${ENCRYPTION_KEY}
  upload-dir: ${UPLOAD_DIR}