package com.dogukanpolat.telemedicine.model.enums;

public enum NotificationType {
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REMINDER_24H,
    APPOINTMENT_REMINDER_1H,
    APPOINTMENT_CANCELLATION,
    APPOINTMENT_RESCHEDULED,
    LAB_RESULTS_READY,
    PRESCRIPTION_REFILL_REMINDER,
    PRESCRIPTION_READY,
    ACCOUNT_VERIFICATION,
    PASSWORD_RESET,
    GENERAL_ANNOUNCEMENT
}
